import { Publication } from "./research";

export const publications: Publication[] = [
  {
    id: "PUB001",
    title: "Deep Learning Approaches for Medical Image Analysis",
    authors: ["Dr. Nguyen Van A", "Dr. Tran Thi B", "Dr. Le Van C"],
    type: "Journal Article",
    journal: "IEEE Transactions on Medical Imaging",
    year: 2024,
    citations: 45,
    impactFactor: 10.6,
    status: "Published",
    doi: "10.1109/TMI.2024.12345",
    project: "PRJ001",
    quartile: "Q1",
    discipline: "Nontraditional Security"
  },
  {
    id: "PUB002",
    title: "Sustainable City Development: A Data-Driven Framework",
    authors: ["Dr. Pham Thi D", "Dr. Hoang Van E"],
    type: "Conference Paper",
    journal: "International Conference on Urban Planning",
    year: 2024,
    citations: 23,
    impactFactor: null,
    status: "Published",
    doi: "10.1145/ICUP.2024.56789",
    project: "PRJ002",
    quartile: "N/A",
    discipline: "Sustainable Development"
  },
  {
    id: "PUB003",
    title: "Quantum Algorithms for Cryptographic Applications",
    authors: ["Dr. Vo Thi F", "Dr. Bui Van G", "Dr. Cao Thi H"],
    type: "Book Chapter",
    journal: "Nature Quantum Information",
    publisher: "IEEE",
    year: 2024,
    citations: 89,
    impactFactor: 15.2,
    status: "Published",
    doi: "10.1038/s41534-024-00234",
    project: "PRJ003",
    quartile: "Q1",
    discipline: "Engineering & IT"
  },
  {
    id: "PUB004",
    title: "Blockchain Technology in Supply Chain Management",
    authors: ["Dr. Dinh Van I", "Dr. Ly Van J"],
    type: "Book",
    journal: "Series in Computer Science and Engineering",
    publisher: "Springer",
    year: 2024,
    citations: 12,
    impactFactor: null,
    status: "Published",
    doi: null,
    project: "PRJ004",
    quartile: "N/A",
    discipline: "Finance"
  },
  {
    id: "PUB005",
    title: "Machine Learning in Healthcare: Current Trends",
    authors: ["Dr. Nguyen Van A", "Dr. Le Van C"],
    type: "Review Article",
    journal: "Journal of Healthcare Engineering",
    publisher: "IEEE",
    year: 2025,
    citations: 0,
    impactFactor: 3.9,
    status: "Under Review",
    doi: null,
    project: "PRJ001",
    quartile: "Q2",
    discipline: "Nontraditional Security"
  },
  {
    id: "PUB006",
    title: "Optimization Techniques for Neural Networks",
    authors: ["Dr. Mai Van K", "Dr. Dang Thi L"],
    type: "Journal Article",
    journal: "Neural Networks",
    year: 2024,
    citations: 34,
    impactFactor: 7.8,
    status: "Published",
    doi: "10.1016/j.neunet.2024.98765",
    project: "PRJ005",
    quartile: "Q1",
    discipline: "Engineering & IT"
  },
  {
    id: "PUB007",
    title: "Digital Transformation in Human Resource Management",
    authors: ["Dr. Pham Van O", "Dr. Tran Thi P"],
    type: "Journal Article",
    journal: "Human Resource Management Review",
    publisher: "Taylor & Francis",
    year: 2024,
    citations: 28,
    impactFactor: 6.2,
    status: "Published",
    doi: "10.1016/j.hrmr.2024.45678",
    project: "PRJ002",
    quartile: "Q1",
    discipline: "Human Resources"
  },
  {
    id: "PUB008",
    title: "Social Media Marketing Effectiveness in Emerging Markets",
    authors: ["Dr. Nguyen Thi M", "Dr. Phan Van N"],
    type: "Journal Article",
    journal: "Journal of Marketing Research",
    year: 2024,
    citations: 31,
    impactFactor: 8.1,
    status: "Published",
    doi: "10.1177/JMR.2024.12345",
    project: "PRJ006",
    quartile: "Q1",
    discipline: "Marketing"
  },
  {
    id: "PUB009",
    title: "Crisis Communication Strategies in the Digital Age",
    authors: ["Dr. Le Van Q", "Dr. Hoang Thi R"],
    type: "Conference Paper",
    journal: "International Communication Association Conference",
    year: 2024,
    citations: 15,
    impactFactor: null,
    status: "Published",
    doi: null,
    project: null,
    quartile: "N/A",
    discipline: "Communication"
  },
  {
    id: "PUB010",
    title: "Cybercrime and Legal Frameworks in Southeast Asia",
    authors: ["Dr. Bui Van S", "Dr. Cao Thi T"],
    type: "Book Chapter",
    journal: "International Journal of Cyber Criminology",
    publisher: "Taylor & Francis",
    year: 2024,
    citations: 19,
    impactFactor: 4.5,
    status: "Published",
    doi: "10.5281/ijcc.2024.98765",
    project: null,
    quartile: "Q2",
    discipline: "Law & Criminology"
  }
];
