import { ResearchProject } from "./research";

export const researchProjects: ResearchProject[] = [
  {
    id: "PRJ001",
    title: "AI-Driven Healthcare Diagnostics",
    pi: "Dr. Nguyen Van A",
    coInvestigators: ["Dr. Tran Thi B", "Dr. Le Van C"],
    type: "Applied Research",
    status: "Active",
    level: "National",
    startDate: "2024-01-15",
    endDate: "2026-01-14",
    funding: "$250,000",
    fundingSource: "Nafosted",
    progress: 45,
    publications: 3,
    department: "Faculty of Nontraditional Security",
    description: "Developing machine learning algorithms for early disease detection and diagnosis in medical imaging."
  },
  {
    id: "PRJ002",
    title: "Sustainable Urban Planning Framework",
    pi: "Dr. Pham Thi D",
    coInvestigators: ["Dr. Hoang Van E"],
    type: "Basic Research",
    status: "Active",
    level: "Ministry",
    startDate: "2024-03-01",
    endDate: "2025-12-31",
    funding: "$180,000",
    fundingSource: "Ministry of Education",
    progress: 62,
    publications: 5,
    department: "Faculty of Management",
    description: "Creating data-driven frameworks for sustainable city development and resource management."
  },
  {
    id: "PRJ003",
    title: "Quantum Computing Applications",
    pi: "Dr. Vo Thi F",
    coInvestigators: ["Dr. Bui Van G", "Dr. Cao Thi H"],
    type: "Applied Research",
    status: "Active",
    level: "National",
    startDate: "2023-09-01",
    endDate: "2026-08-31",
    funding: "$400,000",
    fundingSource: "Ministry of Science and Technology",
    progress: 78,
    publications: 8,
    department: "Faculty of Nontraditional Security",
    description: "Exploring practical applications of quantum computing in cryptography and optimization."
  },
  {
    id: "PRJ004",
    title: "Blockchain in Supply Chain",
    pi: "Dr. Dinh Van I",
    coInvestigators: ["Dr. Ly Van J"],
    type: "Applied Research",
    status: "Completed",
    level: "HSB",
    startDate: "2022-06-01",
    endDate: "2024-05-31",
    funding: "$150,000",
    fundingSource: "Industry Partnership",
    progress: 100,
    publications: 12,
    department: "Faculty of Management",
    description: "Implementing blockchain technology for transparent and efficient supply chain management."
  },
  {
    id: "PRJ005",
    title: "Neural Network Optimization",
    pi: "Dr. Mai Van K",
    coInvestigators: ["Dr. Dang Thi L"],
    type: "Basic Research",
    status: "Pending",
    level: "VNU",
    startDate: "2025-01-01",
    endDate: "2027-12-31",
    funding: "$320,000",
    fundingSource: "VNU",
    progress: 0,
    publications: 0,
    department: "Faculty of Nontraditional Security",
    description: "Advanced research on neural network architecture optimization and efficiency."
  },
  {
    id: "PRJ006",
    title: "Digital Marketing Strategies in Social Media",
    pi: "Dr. Nguyen Thi M",
    coInvestigators: ["Dr. Phan Van N"],
    type: "Applied Research",
    status: "Active",
    level: "HSB",
    startDate: "2024-02-15",
    endDate: "2025-12-31",
    funding: "$120,000",
    fundingSource: "Industry Partnership",
    progress: 55,
    publications: 4,
    department: "Faculty of Marketing and Communication",
    description: "Analyzing consumer behavior and developing effective digital marketing frameworks for social media platforms."
  }
];
