import { Patent } from "./research";

export const patentData: Patent[] = [
  {
    id: "PAT001",
    title: "AI-Based Medical Diagnostic System Using Deep Learning",
    inventors: ["Dr. Nguyen Van A", "Dr. Tran Thi B", "Dr. Le Van C"],
    applicationNumber: "VN2024001234",
    applicationDate: "2024-01-15",
    status: "Granted",
    grantDate: "2024-08-20",
    patentNumber: "VN123456",
    type: "Invention Patent",
    faculty: "Faculty of Nontraditional Security",
    discipline: "Nontraditional Security",
    abstract: "A novel AI-based system for automated medical diagnosis using advanced deep learning algorithms for pattern recognition in medical imaging.",
    country: "Vietnam",
    ipOffice: "National Office of Intellectual Property (NOIP)"
  },
  {
    id: "PAT002",
    title: "Blockchain-Based Supply Chain Tracking Method",
    inventors: ["Dr. Pham Thi D", "Dr. Hoang Van E"],
    applicationNumber: "VN2024002345",
    applicationDate: "2024-03-10",
    status: "Pending",
    grantDate: null,
    patentNumber: null,
    type: "Invention Patent",
    faculty: "Faculty of Management",
    discipline: "Finance",
    abstract: "A decentralized blockchain method for transparent and secure supply chain tracking with real-time verification capabilities.",
    country: "Vietnam",
    ipOffice: "National Office of Intellectual Property (NOIP)"
  },
  {
    id: "PAT003",
    title: "Quantum Encryption Algorithm for Secure Communications",
    inventors: ["Dr. Vo Thi F", "Dr. Bui Van G", "Dr. Cao Thi H"],
    applicationNumber: "US2024098765",
    applicationDate: "2024-02-20",
    status: "Granted",
    grantDate: "2024-09-15",
    patentNumber: "US11,234,567",
    type: "Invention Patent",
    faculty: "Faculty of Nontraditional Security",
    discipline: "Engineering & IT",
    abstract: "A quantum-based encryption algorithm providing enhanced security for digital communications using quantum key distribution.",
    country: "United States",
    ipOffice: "United States Patent and Trademark Office (USPTO)"
  },
  {
    id: "PAT004",
    title: "IoT-Based Smart Agriculture Monitoring System",
    inventors: ["Dr. Mai Van K", "Dr. Dang Thi L"],
    applicationNumber: "VN2024003456",
    applicationDate: "2024-05-08",
    status: "Under Examination",
    grantDate: null,
    patentNumber: null,
    type: "Utility Model",
    faculty: "Faculty of Nontraditional Security",
    discipline: "Sustainable Development",
    abstract: "An IoT-based system for real-time monitoring and optimization of agricultural processes using sensor networks and AI analytics.",
    country: "Vietnam",
    ipOffice: "National Office of Intellectual Property (NOIP)"
  },
  {
    id: "PAT005",
    title: "Digital Marketing Analytics Platform with AI",
    inventors: ["Dr. Nguyen Thi M", "Dr. Phan Van N"],
    applicationNumber: "VN2024004567",
    applicationDate: "2024-06-15",
    status: "Pending",
    grantDate: null,
    patentNumber: null,
    type: "Invention Patent",
    faculty: "Faculty of Marketing and Communication",
    discipline: "Marketing",
    abstract: "An AI-powered platform for comprehensive digital marketing analytics with predictive consumer behavior modeling.",
    country: "Vietnam",
    ipOffice: "National Office of Intellectual Property (NOIP)"
  },
  {
    id: "PAT006",
    title: "Cybersecurity Threat Detection System",
    inventors: ["Dr. Le Van Q", "Dr. Hoang Thi R"],
    applicationNumber: "PCT/VN2024/00123",
    applicationDate: "2024-04-25",
    status: "International Filing",
    grantDate: null,
    patentNumber: null,
    type: "Invention Patent",
    faculty: "Faculty of Nontraditional Security",
    discipline: "Law & Criminology",
    abstract: "An advanced system for real-time detection and prevention of cybersecurity threats using machine learning and behavioral analysis.",
    country: "International (PCT)",
    ipOffice: "World Intellectual Property Organization (WIPO)"
  },
  {
    id: "PAT007",
    title: "Sustainable Energy Management System for Smart Buildings",
    inventors: ["Dr. Bui Van S", "Dr. Cao Thi T"],
    applicationNumber: "VN2023005678",
    applicationDate: "2023-11-10",
    status: "Granted",
    grantDate: "2024-07-05",
    patentNumber: "VN123789",
    type: "Invention Patent",
    faculty: "Faculty of Nontraditional Security",
    discipline: "Sustainable Development",
    abstract: "An intelligent energy management system optimizing power consumption in smart buildings using renewable energy sources.",
    country: "Vietnam",
    ipOffice: "National Office of Intellectual Property (NOIP)"
  },
  {
    id: "PAT008",
    title: "Human Resource Performance Prediction Model",
    inventors: ["Dr. Dinh Van I", "Dr. Ly Van J"],
    applicationNumber: "VN2024006789",
    applicationDate: "2024-07-20",
    status: "Pending",
    grantDate: null,
    patentNumber: null,
    type: "Invention Patent",
    faculty: "Faculty of Management",
    discipline: "Human Resources",
    abstract: "A predictive model for employee performance assessment using AI and big data analytics for HR optimization.",
    country: "Vietnam",
    ipOffice: "National Office of Intellectual Property (NOIP)"
  }
];
