// src/data/studentData.ts

export interface studentdata {
  id: string;
  name: string;
  program: string;
  level: "Bachelor" | "Master" | "PhD";
  year: string;
  gpa: string;
  status: "Active" | "Inactive" | "Graduated";
}

export const sampleStudents: studentdata[] = [
  { id: "S001001", name: "Nguyen Quang Binh", program: "MNS", level: "Master", year: "1", gpa: "3.02", status: "Active" },
  { id: "S001002", name: "Hoang Khanh Binh", program: "DMS", level: "PhD", year: "1", gpa: "3.6", status: "Active" },
  { id: "S001003", name: "Maria Santoso", program: "MNS", level: "Master", year: "1", gpa: "2.95", status: "Active" },
  { id: "S001004", name: "Nguyen Anh Binh", program: "DMS", level: "PhD", year: "1", gpa: "3.46", status: "Active" },
  { id: "S001005", name: "Dang Thanh Dung", program: "MNS", level: "Master", year: "2", gpa: "3.5", status: "Active" },
  { id: "S001006", name: "Nguyen Van Mai", program: "MAC", level: "Bachelor", year: "4", gpa: "2.83", status: "Active" },
  { id: "S001007", name: "Do Duc Hoa", program: "MBA", level: "Master", year: "2", gpa: "2.52", status: "Active" },
  { id: "S001008", name: "Pham Duc Lan", program: "DMS", level: "PhD", year: "2", gpa: "2.7", status: "Active" },
  { id: "S001009", name: "Le Van Mai", program: "DMS", level: "PhD", year: "2", gpa: "2.75", status: "Active" },
  { id: "S001010", name: "Do Anh Lan", program: "MOTE", level: "Master", year: "1", gpa: "3.57", status: "Active" },
  { id: "S001011", name: "Le Khanh An", program: "DMS", level: "PhD", year: "3", gpa: "3.55", status: "Active" },
  { id: "S001012", name: "Nguyen Thanh Lan", program: "HAT", level: "Bachelor", year: "1", gpa: "3.48", status: "Active" },
  { id: "S001013", name: "Nguyen Huy Cuong", program: "DMS", level: "PhD", year: "2", gpa: "2.91", status: "Active" },
  { id: "S001014", name: "Do Quang Mai", program: "MNS", level: "Master", year: "1", gpa: "2.77", status: "Active" },
  { id: "S001015", name: "Hoang Huy Hung", program: "HAT", level: "Bachelor", year: "2", gpa: "3.98", status: "Active" },
  { id: "S001016", name: "Dang Khanh Hung", program: "DMS", level: "PhD", year: "3", gpa: "2.99", status: "Active" },
  { id: "S001017", name: "Emily Johnson", program: "DMS", level: "PhD", year: "2", gpa: "2.94", status: "Active" },
  { id: "S001018", name: "Nguyen Van Mai", program: "DMS", level: "PhD", year: "2", gpa: "3.08", status: "Active" },
  { id: "S001019", name: "Bui Thu An", program: "MBA", level: "Master", year: "1", gpa: "3.6", status: "Active" },
  { id: "S001020", name: "Wei Kim", program: "DMS", level: "PhD", year: "1", gpa: "3.47", status: "Active" },
  { id: "S001021", name: "Nguyen Khanh Dung", program: "MNS", level: "Master", year: "2", gpa: "3.52", status: "Active" },
  { id: "S001022", name: "Ngo Anh Hoa", program: "MOTE", level: "Master", year: "1", gpa: "3.93", status: "Active" },
  { id: "S001023", name: "Dang Van Em", program: "DMS", level: "PhD", year: "2", gpa: "3.47", status: "Active" },
  { id: "S001024", name: "Le Huy Lan", program: "MAC", level: "Bachelor", year: "1", gpa: "2.81", status: "Active" },
  { id: "S001025", name: "Tran Anh Phuong", program: "DMS", level: "PhD", year: "1", gpa: "3.26", status: "Active" },
  { id: "S001026", name: "Dang Huy Em", program: "DMS", level: "PhD", year: "3", gpa: "3.59", status: "Active" },
  { id: "S001027", name: "Tran Minh Mai", program: "DMS", level: "PhD", year: "3", gpa: "3.22", status: "Active" },
  { id: "S001028", name: "Dang Khanh Hung", program: "MOTE", level: "Master", year: "2", gpa: "3.33", status: "Active" },
  { id: "S001029", name: "Daniel Johnson", program: "MBA", level: "Master", year: "1", gpa: "3.79", status: "Active" },
  { id: "S001030", name: "Tran Quang Cuong", program: "MOTE", level: "Master", year: "2", gpa: "3.46", status: "Active" },
  { id: "S001031", name: "Le Thu Hung", program: "DMS", level: "PhD", year: "2", gpa: "3.87", status: "Active" },
  { id: "S001032", name: "Hoang Thu Hoa", program: "MAC", level: "Bachelor", year: "4", gpa: "3.34", status: "Active" },
  { id: "S001033", name: "Tran Minh Em", program: "MOTE", level: "Master", year: "1", gpa: "3.8", status: "Active" },
  { id: "S001034", name: "Do Thi Em", program: "DMS", level: "PhD", year: "3", gpa: "2.82", status: "Active" },
  { id: "S001035", name: "Tran Khanh Phuong", program: "HAS", level: "Bachelor", year: "2", gpa: "2.93", status: "Active" },
  { id: "S001036", name: "Pham Minh Binh", program: "MOTE", level: "Master", year: "1", gpa: "3.52", status: "Active" },
  { id: "S001037", name: "Tran Thi Phuong", program: "DMS", level: "PhD", year: "2", gpa: "2.52", status: "Active" },
  { id: "S001038", name: "Pham Huy Lan", program: "MOTE", level: "Master", year: "1", gpa: "2.5", status: "Active" },
  { id: "S001039", name: "Grace Wilson", program: "MAS", level: "Bachelor", year: "4", gpa: "3.66", status: "Active" },
  { id: "S001040", name: "Hoang Huy Cuong", program: "MET", level: "Bachelor", year: "1", gpa: "3.22", status: "Active" },
  { id: "S001041", name: "Hoang Thu Dung", program: "MET", level: "Bachelor", year: "3", gpa: "3.75", status: "Active" },
  { id: "S001042", name: "Tran Duc Binh", program: "MET", level: "Bachelor", year: "2", gpa: "2.56", status: "Active" },
  { id: "S001043", name: "Vu Duc Lan", program: "MOTE", level: "Master", year: "1", gpa: "2.73", status: "Active" },
  { id: "S001044", name: "Tran Thi Hoa", program: "DMS", level: "PhD", year: "1", gpa: "2.8", status: "Active" },
  { id: "S001045", name: "Le Van Phuong", program: "MET", level: "Bachelor", year: "1", gpa: "3.02", status: "Active" },
  { id: "S001046", name: "Tran Huy Phuong", program: "MNS", level: "Master", year: "2", gpa: "2.62", status: "Active" },
  { id: "S001047", name: "Hana Zhang", program: "MNS", level: "Master", year: "2", gpa: "2.98", status: "Active" },
  { id: "S001048", name: "David Martinez", program: "HAS", level: "Bachelor", year: "2", gpa: "2.62", status: "Active" },
  { id: "S001049", name: "Bui Anh An", program: "MAS", level: "Bachelor", year: "1", gpa: "2.72", status: "Active" },
  { id: "S001050", name: "Nguyen Thi Cuong", program: "MBA", level: "Master", year: "1", gpa: "3.56", status: "Active" },
  { id: "S001051", name: "Do Duc Em", program: "MOTE", level: "Master", year: "1", gpa: "2.8", status: "Active" },
  { id: "S001052", name: "Do Anh Phuong", program: "MNS", level: "Master", year: "2", gpa: "3.49", status: "Active" },
  { id: "S001053", name: "Tran Huy Cuong", program: "MNS", level: "Master", year: "2", gpa: "2.89", status: "Active" },
  { id: "S001054", name: "Do Thi Hoa", program: "MBA", level: "Master", year: "2", gpa: "3.12", status: "Active" },
  { id: "S001055", name: "Hoang Khanh Dung", program: "MOTE", level: "Master", year: "2", gpa: "3.18", status: "Active" },
  { id: "S001056", name: "Somchai Lopez", program: "MNS", level: "Master", year: "1", gpa: "3.9", status: "Active" },
  { id: "S001057", name: "Le Quang Mai", program: "HAS", level: "Bachelor", year: "1", gpa: "3.08", status: "Active" },
  { id: "S001058", name: "Tran Anh Phuong", program: "DMS", level: "PhD", year: "3", gpa: "2.65", status: "Active" },
  { id: "S001059", name: "Pham Thanh Lan", program: "MOTE", level: "Master", year: "1", gpa: "2.55", status: "Active" },
  { id: "S001060", name: "Bui Thu Dung", program: "DMS", level: "PhD", year: "2", gpa: "3.14", status: "Active" },
  { id: "S001061", name: "Ngo Thanh Phuong", program: "MET", level: "Bachelor", year: "2", gpa: "3.42", status: "Active" },
  { id: "S001062", name: "Nguyen Minh Binh", program: "DMS", level: "PhD", year: "1", gpa: "3.99", status: "Active" },
  { id: "S001063", name: "Ngo Anh An", program: "DMS", level: "PhD", year: "3", gpa: "2.88", status: "Active" },
  { id: "S001064", name: "Do Duc An", program: "BNS", level: "Bachelor", year: "3", gpa: "3.36", status: "Active" },
  { id: "S001065", name: "Bui Thanh An", program: "DMS", level: "PhD", year: "2", gpa: "3.51", status: "Active" },
  { id: "S001066", name: "Nguyen Van An", program: "DMS", level: "PhD", year: "1", gpa: "3.08", status: "Active" },
  { id: "S001067", name: "Pham Khanh An", program: "MBA", level: "Master", year: "2", gpa: "3.82", status: "Active" },
  { id: "S001068", name: "John Garcia", program: "MNS", level: "Master", year: "2", gpa: "3.67", status: "Active" },
  { id: "S001069", name: "Pham Thu An", program: "DMS", level: "PhD", year: "1", gpa: "3.6", status: "Active" },
  { id: "S001070", name: "Dang Khanh Cuong", program: "MOTE", level: "Master", year: "2", gpa: "2.62", status: "Active" },
  { id: "S001071", name: "Bui Anh Hoa", program: "MET", level: "Bachelor", year: "2", gpa: "3.21", status: "Active" },
  { id: "S001072", name: "Do Khanh Cuong", program: "DMS", level: "PhD", year: "3", gpa: "2.68", status: "Active" },
  { id: "S001073", name: "Hoang Thanh Dung", program: "DMS", level: "PhD", year: "2", gpa: "3.79", status: "Active" },
  { id: "S001074", name: "Dang Thu Hoa", program: "DMS", level: "PhD", year: "1", gpa: "2.78", status: "Active" },
  { id: "S001075", name: "Hoang Thu Lan", program: "MOTE", level: "Master", year: "1", gpa: "3.69", status: "Active" },
  { id: "S001076", name: "Chan Cruz", program: "DMS", level: "PhD", year: "1", gpa: "3.68", status: "Active" },
  { id: "S001077", name: "Vu Khanh Mai", program: "MBA", level: "Master", year: "2", gpa: "3.32", status: "Active" },
  { id: "S001078", name: "Hoang Duc Dung", program: "MBA", level: "Master", year: "1", gpa: "3.94", status: "Active" },
  { id: "S001079", name: "Dang Minh Mai", program: "MBA", level: "Master", year: "2", gpa: "2.72", status: "Active" },
  { id: "S001080", name: "Le Quang Phuong", program: "MNS", level: "Master", year: "1", gpa: "2.59", status: "Active" },
  { id: "S001081", name: "Pham Duc Hung", program: "HAT", level: "Bachelor", year: "4", gpa: "3.66", status: "Active" },
  { id: "S001082", name: "Hiroshi Tanaka", program: "MBA", level: "Master", year: "1", gpa: "3.39", status: "Active" },
  { id: "S001083", name: "Le Thu Mai", program: "DMS", level: "PhD", year: "3", gpa: "3.46", status: "Active" },
  { id: "S001084", name: "Ngo Huy Hung", program: "MBA", level: "Master", year: "1", gpa: "3.12", status: "Active" },
  { id: "S001085", name: "Ngo Van An", program: "MOTE", level: "Master", year: "1", gpa: "3.44", status: "Active" },
  { id: "S001086", name: "Ngo Khanh Binh", program: "DMS", level: "PhD", year: "3", gpa: "2.67", status: "Active" },
  { id: "S001087", name: "Tran Thu Em", program: "DMS", level: "PhD", year: "3", gpa: "3.43", status: "Active" },
  { id: "S001088", name: "Ngo Minh Dung", program: "DMS", level: "PhD", year: "2", gpa: "2.57", status: "Active" },
  { id: "S001089", name: "Bui Thi Binh", program: "MBA", level: "Master", year: "2", gpa: "3.02", status: "Active" },
  { id: "S001090", name: "Do Duc Phuong", program: "BNS", level: "Bachelor", year: "1", gpa: "2.66", status: "Active" },
  { id: "S001091", name: "Le Huy Binh", program: "MBA", level: "Master", year: "2", gpa: "2.91", status: "Active" },
  { id: "S001092", name: "Hoang Huy Phuong", program: "BNS", level: "Bachelor", year: "3", gpa: "3.67", status: "Active" },
  { id: "S001093", name: "Bui Van An", program: "DMS", level: "PhD", year: "2", gpa: "2.87", status: "Active" },
  { id: "S001094", name: "Sakura Park", program: "MOTE", level: "Master", year: "1", gpa: "3.11", status: "Active" },
  { id: "S001095", name: "Do Huy Phuong", program: "MOTE", level: "Master", year: "2", gpa: "3.64", status: "Active" },
  { id: "S001096", name: "Hoang Khanh Phuong", program: "DMS", level: "PhD", year: "1", gpa: "2.79", status: "Active" },
  { id: "S001097", name: "Bui Duc Lan", program: "DMS", level: "PhD", year: "2", gpa: "3.31", status: "Active" },
  { id: "S001098", name: "Dang Thu Hoa", program: "MBA", level: "Master", year: "2", gpa: "2.71", status: "Active" },
  { id: "S001099", name: "Hoang Anh Hoa", program: "MAC", level: "Bachelor", year: "3", gpa: "3.05", status: "Active" },
  { id: "S001100", name: "Siti Chai", program: "MOTE", level: "Master", year: "1", gpa: "3.28", status: "Active" },
];
